version: '3'

services:
  app:
    container_name: express.workouts.api.v1
    restart: always
    build: ../.
    image: express.workouts.api
    environment:
      - SERVER_PORT=5000
      - PORT=5000
      - APP_NAME=Workouts REST API
      - APP_VER=0.0.1
      - NODE_ENV=production
      - LOGGING=production
      - MONGDB_HOST=mongo:27017/workouts
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
